[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11.0
builtin_box_drawing = true

[window]
opacity = 0.8

[colors.primary]
background = "#1F1F1F"
foreground = "#FFFFFF"

[colors.normal]
black   = "#073642"
red     = "#dc322f"
green   = "#859900"
yellow  = "#b58900"
blue    = "#268bd2"
magenta = "#d33682"
cyan    = "#2aa198"
white   = "#FFFFFF"

[colors.bright]
black   = "#002b36"
red     = "#cb4b16"
green   = "#586e75"
yellow  = "#657b83"
blue    = "#839496"
magenta = "#6c71c4"
cyan    = "#93a1a1"
white   = "#FFFFFF"

[terminal.shell]
program = "/bin/zsh"
